export const adminStrings = {
  adminPanel: "Admin Panel",
  onlyAdminAccess: "Only admins can access this page.",
};

export const authStrings = {
  labels: {
    email: "Email",
    password: "Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    rememberMe: "Remember me",
    enterEmailLabel: "Enter Email Label",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm Password",
  },
  placeholders: {
    email: "admin@hrms.com",
    password: "Password",
    enterEmail: "Enter your email",
    enterEmailPlaceholder: "Enter your email",
  },
  titles: {
    login: "LOGIN",
    forgotPassword: "Forgot Your Password",
    resetPassword: "Reset Password",
    checkEmail: "Check Your Email",
    forgotPasswordTitle: "Forgot Your Password",
    checkEmailTitle: "Check Your Email",
    resetPasswordTitle: "Reset Password",
  },
  messages: {
    invalidCredentials: "Invalid email or password",
    forgotPasswordInstructions: "Enter your email address, and we'll send you instructions to reset your password.",
    checkEmailInstructions: "We've sent password reset instructions to:",
    checkEmailSpam: "If you don't see the email, check your spam folder or try again.",
    resetPasswordInstructions: "Enter your new password below.",
    sending: "Sending...",
    resetting: "Resetting...",
    sendingResetLink: "Sending reset link...",
    resetLinkSent: "Reset link sent successfully!",
    failedToSendResetLink: "Failed to send reset link",
    invalidToken: "Invalid or missing reset token",
    passwordResetSuccessful: "Password reset successful!",
    failedToResetPassword: "Failed to reset password",
    requestResetLink: "Request reset link",
  },
};

export const profileStrings = {
  titles: {
    myProfile: "My Profile",
    userInformation: "User Information",
  },
  labels: {
    name: "Name",
    role: "Role",
    userId: "User ID",
    currentCompany: "Current Company",
    companyCode: "Code",
  },
};

export const employeeStrings = {
  titles: {
    addEmployee: "Add Employee",
    editEmployee: "Edit Employee",
    employeeDetails: "Employee Details",
    basicInfo: "Basic Information",
    backgroundInfo: "Background Information",
    otherDetails: "Other Details",
    contactInfo: "Contact Info",
    nmcInstructions: "NMC Information",
    training: "Training",
    qualifications: "Qualifications",
    reviews: "Reviews",
  },
  labels: {
    empId: "Employee ID",
    firstName: "FirstName",
    surname: "Surname",
    knownAs: "Known As",
    title: "Title",
    pronouns: "Pronounces",
    dob: "D.O.B",
    gender: "Gender",
    startDate: "Start Date",
    nhsNumber: "NHS Number",
    badgeNumber: "Badge Number",
    maritalStatus: "Marital Status",
    nationality: "Nationality",
    religion: "Religion",
    ethnicOrigin: "Ethnic Origin",
    department: "Department",
    crbNumber: "CRB Number",
    status: "Status",
    crbDate: "CRB Date",
    jobTitle: "Job Title",
    crbRiskAssessed: "CRB Risk Assessed",
    residentPermitExpiry: "Resident Permit Expiry Date",
    crbCleared: "CRB Cleared",
    niNumber: "NI Number",
    supervisor: "Supervisor",
    namedNurse: "Named Nurse",
    nmcNumber: "NMC Number",
    nmcExpiry: "NMC Expiry",
    passportNumber: "Passport Number",
    passportExpiryDate: "Passport Expiry Date",
    address: "Employee Address",
    tel1: "Tel 1",
    tel2: "Tel 2",
    mobile: "Mobile",
    fax: "Fax",
    personalEmail: "Personal Email",
    businessEmail: "Business Email",
    allContacts: "All Contacts",
    mapFromExisting: "Map from existing",
    renewalDate: "Renewal Date",
  },
  placeholders: {
    search: "Search by name, job title, department",
    allDepartment: "All Department",
    jobStatus: "Job Status",
    employeeStatus: "Employee Status",
    selectContactType: "Select contact type",
    searchPlaceholder: "Search by name, job title, department",
  },
  filterPlaceholders: {
    allDepartment: "All Department",
    jobStatus: "Job Status",
    employeeStatus: "Employee Status",
    jobTitle: "Job Title",
  },
  columns: {
    firstName: "Name",
    surname: "Name",
    knownAs: "Known As",
    jobTitle: "Job Title",
    department: "Department",
    startDate: "Start Date",
    jobStatus: "Job Status",
  },
  statusOptions: {
    current: "Current",
    archived: "Archived",
  },
  messages: {
    deleteTitle: "Delete Employee",
    deleteConfirmSingle: "Are you sure you want to delete {name}?",
    deleteConfirmGeneric: "Are you sure you want to delete this employee?",
    noIncidents: "No incidents found matching your filters.",
    noNMCPresent: "No NMC Records",
    addressCopied: "Employee Address copied to clipboard",
  },
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  COMPANY: {
    BASE: "/company",
  },
  TRADE_NAME: {
    BASE: "/trade-name",
    WITH_COMPANY: "/trade-name/with-company",
  },
  EMPLOYEES: {
    BASE: "/employees",
    CONTACTS: "/contacts",
    CONTACT_ASSOCIATIONS: "/contact-associations",
    CONTACT_CATEGORIES: "/contact-categories",
  },
  RESIDENTS: {
    BASE: "/residents",
    CONTACTS: "/contacts",
    CONTACT_ASSOCIATIONS: "/contact-associations",
    CONTACT_CATEGORIES: "/contact-categories",
  },
  TRAINING: {
    BASE: "/trainings",
    GROUPED_COURSE: "/trainings/grouped/course",
    SUMMARY: "/trainings/summary",
    COURSES: "/training-courses",
  },
  QUALIFICATIONS: {
    BASE: "/qualifications",
  },
  MESSAGING: {
    SEND: "/messaging/send",
    DRAFT: "/messaging/draft",
    LIST: "/messaging/list",
    BULK_MOVE: "/messaging/bulk/move",
    BULK_READ: "/messaging/bulk/read",
    BULK_UNREAD: "/messaging/bulk/unread",
    BULK_ARCHIVE: "/messaging/bulk/archive",
    BULK_UNARCHIVE: "/messaging/bulk/unarchive",
    BULK_DELETE: "/messaging/bulk/delete",
    BULK_RESTORE: "/messaging/bulk/restore",
    BULK_HARD_DELETE: "/messaging/bulk/hard-delete",
    BASE: "/messaging",
  },
  MASTER_DATA: {
    TITLES: "/titles",
    JOB_STATUSES: "/job-statuses",
    GENDERS: "/genders",
    RELIGIONS: "/religions",
    ETHNIC_ORIGINS: "/ethnic-origins",
    MARITAL_STATUSES: "/marital-statuses",
    DEPARTMENTS: "/departments",
    JOB_TITLES: "/job-titles",
    PRONOUNS: "/pronouns",
    ALL: "/master-data/all",
    EMPLOYEES: "/master-data/all/employees",
  },
} as const;
