export const globalStrings = {
  backToDashboard: "Back to Dashboard",
  logout: "Logout",
  cancel: "Cancel",
  save: "Save",
  delete: "Delete",
  submit: "Submit",
  loading: "Loading...",
  rememberMe: "Remember me",
  forgotPassword: "Forgot password?",
  login: "LOGIN",
  backToLogin: "Back to login",
  search: "Search",
  export: "Export",
  view: "View",
  edit: "Edit",
  archive: "Archive",
  unarchive: "Unarchive",
  createNew: "Create New",
  confirmDelete: "Delete Confirmation",
  sureToDelete: "Are you sure you want to delete this item?",
  welcomeBack: "Welcome Back !!",
  noData: "No data available",
  noResultsFound: "No results found",
  noTrainingRecords: "No training records found.",
  noContactsFound: "No contacts found",
  noQualificationsFound: "No qualifications found.",
  noContactsAssociated: "No contacts associated",
  page: "Page",
  of: "of",
  sortBy: "Sort By",
  ascending: "Ascending",
  descending: "Descending",
  clear: "Clear",
  searchEllipsis: "Search...",
  selectEllipsis: "Select...",
  selectEmployee: "Select Employee",
  selectDate: "Select date",
  next: "Next",
  previous: "Previous",
  all: "All",
  none: "None",
  basic: "Basic",
  extra: "Extra",
  attachments: "Attachments",
  print: "Print",
  addAndUpdate: "Add & Update",
  new: "New",
  assignTraining: "Assign Training",
  addQualification: "Add Qualification",
};
